version: 2
jobs:
  build:
    docker:
      - image: electronuserland/builder:wine-chrome
    steps:
      - checkout
      - run:
          name: Install node
          command: npm i -g n && n 12.4
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - node-v2-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - node-v2-{{ .Branch }}-
            - node-v2-
      - run:
          name: "Pull Submodules"
          command: |
            git submodule update --init --recursive --remote
      - run:
          name: Install CMAKE
          command: |
            wget https://cmake.org/files/v3.13/cmake-3.13.3-Linux-x86_64.tar.gz
            tar -xvzf cmake-3.13.3-Linux-x86_64.tar.gz
            chmod +x ./cmake-3.13.3-Linux-x86_64/bin/ccmake
            chmod +x ./cmake-3.13.3-Linux-x86_64/bin/cmake
            chmod +x ./cmake-3.13.3-Linux-x86_64/bin/cpack
            chmod +x ./cmake-3.13.3-Linux-x86_64/bin/ctest
            DIR=$(pwd)
            ln -s $DIR/cmake-3.13.3-Linux-x86_64/bin/ccmake /usr/bin/ccmake
            ln -s $DIR/cmake-3.13.3-Linux-x86_64/bin/cmake /usr/bin/cmake
            ln -s $DIR/cmake-3.13.3-Linux-x86_64/bin/cpack /usr/bin/cpack
            ln -s $DIR/cmake-3.13.3-Linux-x86_64/bin/ctest /usr/bin/ctest
      - run:
          name: Install Dependices
          command: npm install
      - run:
          name: Run Tests
          command: npm test
      - save_cache:
          paths:
            - node_modules
          key: node-v2-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run:
          name: Build Electron Packages
          command: npm run electron-pack
      - run:
          name: Run E2E Tests
          command: npm run e2e-test-ci
      - run:
          name: Deploy master to AWS S3
          command: |
            if [ "$CIRCLE_BRANCH" == "master" ];
            then
              ./cd.sh
            fi

