version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.4
    steps:
      - checkout
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - node-v1-{{ .Branch }}-
            - node-v1-
      - run:
          name: Install Dependices
          command: npm install
#      - run:
#          name: Run Tests
#          command: npm test
      - save_cache:
          paths:
            - node_modules
          key: node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run:
          name: Build Electron Packages
          command: npm run electron-pack
      - run:
          name: Deploy master to AWS S3
          command: |
            if [ "$CIRCLE_BRANCH" == "master" ];
            then
              ./cd.sh
            fi

