version: 2
jobs:
  build:
    docker:
      - image: electronuserland/builder:wine-chrome
    steps:
      - checkout
      - run:
          name: Install node
          command: npm i -g n && n 12.4
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - node-v2-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - node-v2-{{ .Branch }}-
            - node-v2-
      - run:
          name: Install Dependices
          command: npm install
      - run:
          name: Run Tests
          command: npm test
      - save_cache:
          paths:
            - node_modules
          key: node-v2-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run:
          name: Build Electron Packages
          command: npm run electron-pack
      - run:
          name: Run E2E Tests
          command: npm run e2e-test-ci
      - run:
          name: Deploy master to AWS S3
          command: |
            if [ "$CIRCLE_BRANCH" == "master" ];
            then
              ./cd.sh
            fi

